FROM ros:noetic-perception

RUN ROS_DISTRO="noetic"

# ==================================================================
# Ubuntu Setup
# (If some of these are unecessary - migrate to dev)
# ------------------------------------------------------------------
RUN \
    apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    software-properties-common \
    apt-utils \
    && \
    APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    # TERMINAL TOOLS
    nano \
    vim \
    tmux \
    # BUILD TOOLS
    build-essential \
    ca-certificates \
    # DOWNLOAD TOOLS
    curl \
    wget \
    # COMPILERS
    g++ \
    cmake \
    # VERSION CONTROL
    git \
    # NETWORK TOOLS
    iputils-ping \
    net-tools \
    # ==================================================================
    # Setup Python3.8 with pip
    # ------------------------------------------------------------------
    && APT_INSTALL="apt-get install -y --no-install-recommends" \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    && DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    python3.8 \
    python3.8-dev \
    python3-pip \
    python3-yaml \
    && python3.8 -m pip install --upgrade pip wheel \
    && python3.8 -m pip install setuptools \
    && python3.8 -m pip install --ignore-installed pyyaml \
    && ln -s /usr/bin/python3.8 /usr/local/bin/python \
    && ln -s /usr/bin/python3.8 /usr/local/bin/python3 \
    # ==================================================================
    # Install ros/catkin packages
    # ------------------------------------------------------------------
    && PIP_INSTALL="python3 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    # ROS
    rospkg \
    catkin_pkg \
    # catkin_tools \
    # AWS
    boto3 \
    wget \
    awscli \
    google-cloud-speech==1.3.2 \
    dialogflow \
    google-api-python-client \
    # TTS
    gdown \
    inflect \
    sounddevice \
    && rm -rf /var/lib/apt/lists/* 

# ==================================================================
# Cmake Setup
# (only needed for armv7 due to cmake bug with qemu. Future cmake >= 3.19
# may fix this without source rebuild once its available on the ubuntu repo.)
# See: https://gitlab.kitware.com/cmake/cmake/-/issues/20568
# ------------------------------------------------------------------
RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
    && case "${dpkgArch##*-}" in \
    amd64) ARCH='x64';; \
    arm64) ARCH='arm64';; \
    armhf) ARCH='armv7';; \
    i386) ARCH='x86';; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac; \
    \
    if [ "$ARCH" = 'armv7' ]; then \
        export CFLAGS="-D_FILE_OFFSET_BITS=64"; \
        export CXXFLAGS="-D_FILE_OFFSET_BITS=64"; \
        version=3.18; \
        build=4; \
        cd '/tmp'; \
        wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz; \
        tar -xzf cmake-$version.$build.tar.gz; \
        cd cmake-$version.$build/; \
        ./bootstrap; \
        make -j$(nproc); \
        make install; \
        cd ../; \
        rm -r cmake-$version.$build.tar.gz cmake-$version.$build; \
        cmake --version; \
    fi;

WORKDIR /root/
RUN git clone https://github.com/catkin/catkin_tools.git
RUN pip install -r catkin_tools/requirements.txt --upgrade
WORKDIR /root/catkin_tools/
RUN python setup.py install --record install_manifest.txt
# ==================================================================
# Harmoni packages
# - Cordial Prerequisites
# - Audio Common Prerequisites
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    # CORIDAL INSTALL
    nodejs \
    npm \
    vorbis-tools python-pygame \
    libboost-all-dev \
    # GSTREAMER (needed for audio_common)
    libgstreamer1.0-0 gstreamer1.0-dev gstreamer1.0-tools gstreamer1.0-doc \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio \
    libgstreamer-plugins-base1.0-dev \
    # PYAUDIO
    portaudio19-dev ffmpeg \
    && npm install http-server -g \
    # && ln -s /usr/bin/nodejs /usr/bin/node \ Already exists
    && PIP_INSTALL="python3.8 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    packaging==19.1 \
    soundfile \
    # empy \ Already exists
    PyAudio \
    && pip install -U Pillow \
    && python3.8 -m pip install --force-reinstall numpy \
    # ==================================================================
    # Install the Ros packages needed for Harmoni
    # ------------------------------------------------------------------
    && APT_INSTALL="apt-get install -y --no-install-recommends" && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    ros-$ROS_DISTRO-rosbridge-server \
    # ros-$ROS_DISTRO-dynamixel-msgs \ Doesn't exist in noetic
    ros-$ROS_DISTRO-audio-common \
    --reinstall python3-pkg-resources \
    && \
    rm -rf /var/lib/apt/lists/* /tmp/*
