FROM harmoniteam/harmoni:kinetic-core

# ==================================================================
# Abstractions for apt installation
RUN \
    APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    zsh \
    unzip \
    # VERSION CONTROL
    git-gui \
    meld \
    # BASIC EDITORS
    gedit \
    vim \
    fonts-powerline \
    emacs \
    nano \
    nautilus \
    # TERMINAL TOOLS
    terminator \
    tmux \
    sudo \
    # MISC. TOOLS
    htop \
    vlc \
    python-keybinder \
    python-notify \
    # PYAUDIO
    portaudio19-dev libportaudio2 libportaudiocpp0\
    ffmpeg libav-tools \
    # GRAPHICS UTILS
    libcanberra-gtk-module \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    && sed -i 's/geteuid/getppid/' /usr/bin/vlc \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Setup Python3.6 with pip, virtualenv
RUN \
    APT_INSTALL="apt-get install -y --no-install-recommends" \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    && DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    python3.6-dev \
    && python3.6 -m pip install \
    pyaudio \
    # ROS
    pyaml \
    empy \
    # AWS
    boto3 \
    awscli \
    # DATA SCIENCE TOOLS
    numpy \
    pandas \
    sklearn \
    statsmodels \
    hmmlearn \
    pmdarima \
    matplotlib \
    dill \
    requests \
    schedule \
    freezegun \
    func_timeout \
    datetimerange \
    jupyterlab \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Setup Pycharm
RUN \
    wget https://download.jetbrains.com/python/pycharm-community-2019.2.5.tar.gz?_ga=2.206607891.1099553149.1574619599-1281313269.1574206878 \
    && mv pycharm-community-* pycharm-community.tar.gz \
    && tar xfz pycharm-*.tar.gz -C /opt/ \
    && rm pycharm-community.tar.gz \
    && echo 'alias pycharm="/opt/pycharm-community-2019.2.5/bin/pycharm.sh"' >> /root/.bashrc 

# ==================================================================
# Install Visual Studio Code
RUN \
    apt-get update -y \
    && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg \
    && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg \
    && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' \
    && apt-get update -y \
    && apt-get install -y code \
    && rm -rf /var/lib/apt/lists/* 