#!/bin/bash
FROM arm32v7/ubuntu:xenial

# ==================================================================
# Abstractions for apt installation
RUN \
    apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    software-properties-common \
    apt-utils \
    && \
    APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    # BUILD TOOLS
    build-essential \
    ca-certificates \
    gfortran \
    libopenblas-dev \
    liblapack-dev \
    # DOWNLOAD TOOLS
    curl \
    wget \
    # COMPILERS
    g++ \
    cmake \
    # VERSION CONTROL
    git \
    # BASIC EDITORS
    vim \
    emacs \
    nano \
    # TERMINAL TOOLS
    terminator \
    tmux \
    sudo \
    # MISC. TOOLS
    vlc \
    htop \
    # PYAUDIO
    portaudio19-dev libportaudio2 libportaudiocpp0\
    ffmpeg libav-tools \
    # GRAPHICS UTILS
    libcanberra-gtk-module \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    && sed -i 's/geteuid/getppid/' /usr/bin/vlc \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Setup Python3.6 with pip, virtualenv
RUN \
    APT_INSTALL="apt-get install -y --no-install-recommends" \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    && DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    python3.6 \
    python3.6-dev \
    python3-pip \
    #python3-virtualenv \
    # ROS
    python3-yaml \
    && python3.6 -m pip install --upgrade pip \
    && python3.6 -m pip install \
    setuptools \
    && python3.6 -m pip install \
    pyaudio \
    # ROS
    pyaml \
    empy \
    rospkg \
    catkin_pkg \
    catkin_tools \
    # AWS
    boto3 \
    awscli \
    # DATA SCIENCE TOOLS
    pandas \
    #sklearn \
    #statsmodels \
    #matplotlib \
    dill \
    requests \
    schedule \
    #freezegun \
    func_timeout \
    datetimerange \
    #jupyterlab \
    && python3.6 -m pip install --ignore-installed pyyaml \
    && rm -rf /var/lib/apt/lists/* 



# ==================================================================
# For convenience add a source script to bashrc and update without clearing
RUN \
    echo 'source /root/.dev_setup_script.sh' >> /root/.bashrc 
# && apt-get update -y && apt-get upgrade -y


# ==================================================================
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
ENTRYPOINT ["/usr/local/bin/dumb-init","--rewrite","15:10","--"]
