# This is a configuration file describing the names of the child of each controller

routers:
  #sensor: ["microphone"]
  #dialogue: ["lex"]
  actuator: ["speaker"]
  #sensor: ["microphone", "rgbd_camera", "chest_camera"]
  #dialogue: ["lex", "dialogflow", "meena"]
  #detector: ["skeleton", "object", "stt", "face"]
  #actuator: ["tts", "speaker", "head_pose", "gesture", "gaze", "screen_face"]

# This is the configuration setting for the behavior interface
# Here are listed the module it could subscribe to
subscribers: 
  skeleton: point3d,
  stt: string,
  object: point3d,
  face: point3d
