# This is a configuration file describing the id of the child of each repo
harmoni:
  lex : ["default"]
  tts: ["default"]
  web: ["default"]
  #detectors: stt:[] face_detect:[]
  stt: ["default"]
  face_detect: ["default"]
pc:
  microphone: ["default"]
  camera : ["default"]
  face: ["default"]
  speaker: ["default"]
