# This is a configuration file describing the id of the child of each repo
repo:
  harmoni:
    lex : ["def"]
    tts: ["def"]
    web: ["def"]
    stt: ["def"]
  pc:
    microphone: ["def"]
    camera : ["def"]
    face: ["def"]
    speaker: ["def"]
