# This is a configuration file describing the names of the child of each router
routers:
  sensor: ["microphone"]
  dialogue: ["lex", "web"]
  actuator: ["face", "speaker", "tts", "web"]
  #detector: ["skeleton", "object", "stt", "face"]

# Here are listed the module it could subscribe to
subscribers: 
  skeleton: point3d,
  stt: string,
  object: point3d,
  face: point3d

