version: "3.7"

services:
  harmoni_hardware:
    container_name: harmoni_hardware
    build:
      context: .
      dockerfile: dockerfiles/arm/harmoni/dockerfile
      network: host
    image: harmoniteam/lightweight:harmoni
    init: true
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
      ROS_DISTRO: kinetic
      IS_DOCKER_ENV: "true"
      CATKIN_WS: harmoni_catkin_ws
      ROS_HOSTNAME: harmoni_hardware
      ROS_MASTER_URI: http://172.18.3.4:11311
    privileged: true
    networks:
      ros_net:
        ipv4_address: 172.18.3.5
    hostname: ros_hardware
    depends_on:
      - "harmoni_core"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    volumes:
      - ../HARMONI/:/root/local_mount/HARMONI/
      # Configuration
      - ./dockerfiles/config/setup_script.sh:/root/.setup_script.sh
      - ./dockerfiles/config/dev_setup_script.sh:/root/.dev_setup_script.sh
      - ./dockerfiles/config/asoundrc:/root/.asoundrc
      # Other
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.config/terminator/config:/root/.config/terminator/config
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh/:/root/.ssh:ro
      - ~/.vimrc:/root/.vimrc:ro
      - ~/.vim/:/root/.vim/:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/harmoni_catkin_ws/src/HARMONI
    command: bash -c "
      terminator -ue \"cd ../HARMONI-hardware && echo 'Entering harmoni_hardware Container... \\n start with rlhardwareservices' && bash\""

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24

volumes:
  harmoni_catkin_ws:
