version: "3.7"

services:
  harmoni_full:
    container_name: harmoni_full
    build:
      context: .
      dockerfile: dockerfiles/harmoni/kinetic/full/dockerfile #substitute $ROS_DISTRO with kinetic for now.
      network: host
    image: harmoniteam/harmoni:kinetic-full
    init: true
    environment:
      DISPLAY: $DISPLAY
      ROS_DISTRO: kinetic
      #ROS_IP: "192.168.100.2"
      ROS_MASTER_URI: http://192.168.100.1:11311
      IS_DOCKER_ENV: "true"
      CATKIN_WS: harmoni_catkin_ws
    # network_mode: "host"
    ports:
      - "11312:11312"
      - "33691:33691"
      - "8081:8081" #harmoni_face
      - "8082:8082" #harmoni_web
    devices:
#      - /dev/dri:/dev/dri
#      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0 #the camera is connected to the NUC
    volumes:
      # - harmoni_catkin_ws:/root/harmoni_catkin_ws
      - ../HARMONI/:/root/local_mount/HARMONI/
      # Configuration
      - ~/.aws:/root/.aws/
      - ./dockerfiles/config/.asoundrc:/root/.asoundrc
      - ~/.gcp/private-keys.json:/root/.gcp/private-keys.json
      # Other
      - /home/.ssh/:/root/.ssh:ro 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/harmoni_catkin_ws/src/HARMONI
    command:
      tail  -f /dev/null
      #  bash -c "terminator -ue \"echo 'Entering harmoni_full Container... \\n start with roscore and rlharmoniservices' && bash\""

volumes:
    harmoni_catkin_ws:

