version: '3.4'

services:
    ros_dev:
        build:
            context: .
            dockerfile: dockerfiles/ros-kinetic-dev
            network: host
        image: ros-dev:latest
        environment:
          DISPLAY: $DISPLAY
          QT_GRAPHICSSYSTEM: native
          ROS_DISTRO: kinetic
          ROS_MASTER_URI: $ROS_MASTER_URI
          IS_DOCKER_ENV: "true"
          PROJECT: harmoni_catkin_ws
        privileged: true
        network_mode: host
        devices: 
          - /dev/dri:/dev/dri
          - /dev/snd:/dev/snd
          - /dev/video0:/dev/video0
        volumes:
          - audio:/root/audio
          - ../../../../w2l/model:/root/model
          - wav2letter:/root/wav2letter
          - ../../:/root/ws/harmoni_catkin_ws
          # IDE
          - pycharm_config:/root/.PyCharmCE2019.3/
          - visual_code_config:/root/.visual_code/
          - ~/.vscode/:/root/.vscode/
          # Configuration
          - ./dockerfiles/config/setup_script.sh:/root/.setup_script.sh
          - ./dockerfiles/config/dev_setup_script.sh:/root/.dev_setup_script.sh
          # Other
          #- ./shared/:/root/shared/
          - ~/.gitconfig/:/root/.gitconfig/:ro
          - ~/.vimrc:/root/.vimrc:ro
          - ~/.vim/:/root/.vim/:ro
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        working_dir: /root/ws/harmoni_catkin_ws/src/HARMONI
        command: bash -c "terminator -ue \"echo 'Entering Docker Container...' && bash\""
    w2l_ros:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-W2L-Inf-Ros
            network: host
        image: w2l-ros-inf:latest
        environment:
            DISPLAY: $DISPLAY
            QT_GRAPHICSSYSTEM: native
            ROS_DISTRO: kinetic
            ROS_MASTER_URI: $ROS_MASTER_URI
            IS_DOCKER_ENV: "true"
            PROJECT: harmoni_catkin_ws
        privileged: true
        network_mode: host
        volumes:
            - audio:/root/audio
            - ../../../../w2l/model:/root/model
            - ../../:/root/ws/harmoni_catkin_ws
            - wav2letter:/root/wav2lettesr
            # Configuration
            - ./dockerfiles/config/setup_script.sh:/root/.setup_script.sh
            - ./dockerfiles/config/dev_setup_script.sh:/root/.dev_setup_script.sh
            # Other
            #- ./shared/:/root/shared/
            - ~/.gitconfig/:/root/.gitconfig/:ro
            - ~/.vimrc:/root/.vimrc:ro
            - ~/.vim/:/root/.vim/:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        working_dir: /root/wav2letter
        command: bash -c "terminator -ue \"echo 'Entering Docker Container...' && bash\""


volumes:
    pycharm_config:
    visual_code_config:
    aws_config:
    audio:
    wav2letter:
