#!/bin/bash
FROM ros:kinetic-ros-base-xenial

RUN ROS_DISTRO="kinetic"

# ==================================================================
# Ubuntu Setup
# (If some of these are unecessary - migrate to dev)
# ------------------------------------------------------------------
RUN \
    apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    software-properties-common \
    apt-utils \
    && \
    APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    # BUILD TOOLS
    build-essential \
    ca-certificates \
    # DOWNLOAD TOOLS
    curl \
    wget \
    # COMPILERS
    g++ \
    cmake \
    # VERSION CONTROL
    git \
    # NETWORK TOOLS
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Setup Python3.6 with pip, virtualenv
# ------------------------------------------------------------------
RUN \
    APT_INSTALL="apt-get install -y --no-install-recommends" \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
    && DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    python3.6 \
    python3-pip \
    python3-yaml \
    && python3.6 -m pip install --upgrade pip \
    && python3.6 -m pip install setuptools \
    && python3.6 -m pip install --ignore-installed pyyaml \
    && ln -s /usr/bin/python3.6 /usr/local/bin/python3 \
    && ln -s /usr/bin/python3.6 /usr/local/bin/python \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Install rosbuild/catkin packages
# ------------------------------------------------------------------
RUN \
    PIP_INSTALL="python3 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    rospkg \
    catkin_pkg \
    catkin_tools \
    # AWS
    boto3 \
    awscli \
    && rm -rf /var/lib/apt/lists/* 


# ==================================================================
# Harmoni packages
# - Cordial Prerequisites
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    nodejs \
    npm \
    vorbis-tools python-pygame python-requests python-serial ros-kinetic-tf python-gst-1.0 python-scipy \
    libboost-all-dev \
    # GSTREAMER (needed for audio_common)
    libgstreamer1.0-0 gstreamer1.0-dev gstreamer1.0-tools gstreamer1.0-doc \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio \
    libgstreamer-plugins-base1.0-dev \
    && \
    npm install http-server -g && \
    ln -s /usr/bin/nodejs /usr/bin/node

RUN \
    PIP_INSTALL="python3.6 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    packaging==19.1 \
    empy \
    soundfile
# dlib \
# imutils \
# opencv-python


# ==================================================================
# Install the Ros packages needed for Harmoni
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    ros-$ROS_DISTRO-rosbridge-server \
    # ros-$ROS_DISTRO-audio-common \
    # ros-$ROS_DISTRO-dynamixel-msgs \
    && \
    rm -rf /var/lib/apt/lists/* /tmp/*


# ==================================================================
# Clone Harmoni and Audio Common
# ------------------------------------------------------------------
ENV ROS_WS /root/harmoni_catkin_ws
RUN mkdir -p $ROS_WS/src
WORKDIR $ROS_WS

RUN git -C src clone \
    -b develop \
    https://github.com/interaction-lab/HARMONI.git 

RUN git -C src clone \
    -b master \
    https://github.com/ros-drivers/audio_common.git


# ==================================================================
# Build Harmoni and Audio from source
# ------------------------------------------------------------------
RUN catkin config \
    --extend /opt/ros/$ROS_DISTRO \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.6 \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m \
    -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
    && \
    catkin build

RUN mkdir -p /root/local_mount/
RUN ln -s /root/harmoni_catkin_ws/src/HARMONI /root/local_mount/


# ==================================================================
# For convenience add a source script to bashrc and update without clearing
# ------------------------------------------------------------------
RUN \
    echo 'source /setup_script.sh' >> /root/.bashrc \
    && apt-get update -y && apt-get upgrade -y

# setup entrypoint and bash setup script
COPY ./dockerfiles/config/harmoni_entrypoint.sh /
COPY ./dockerfiles/config/setup_script.sh /

ENTRYPOINT ["/harmoni_entrypoint.sh"]
CMD ["bash"]


# ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
# RUN chmod +x /usr/local/bin/dumb-init
# ENTRYPOINT ["/usr/local/bin/dumb-init","--rewrite","15:10","--"]