#!/bin/bash
FROM cmbirmingham/ros-kinetic-lightweight:latest


# ==================================================================
# harmoni packages
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    nodejs \
    npm \
    libboost-all-dev \
    libgstreamer1.0-0 gstreamer1.0-dev gstreamer1.0-tools gstreamer1.0-doc \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio \
    libgstreamer-plugins-base1.0-dev \
    && \
    npm install http-server -g && \
    ln -s /usr/bin/nodejs /usr/bin/node \
    && \
    PIP_INSTALL="python3.6 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    packaging==19.1 \
    soundfile \
    dlib \
    imutils \
    opencv-python \
    && \
    # ==================================================================
    # install ros packages for harmoni
    # ------------------------------------------------------------------
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
    ros-$ROS_DISTRO-rosbridge-server \
    ros-$ROS_DISTRO-audio-common \
    ros-$ROS_DISTRO-dynamixel-msgs \
    build-essential \
    && \
    rm -rf /var/lib/apt/lists/* /tmp/*




ENV ROS_WS /root/harmoni_catkin_ws
RUN mkdir -p $ROS_WS/src
WORKDIR $ROS_WS

RUN git -C src clone \
    -b develop \
    https://github.com/interaction-lab/HARMONI.git 


RUN git -C src clone \
    -b kinetic \
    https://github.com/ros-perception/vision_opencv.git

RUN ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py35.so /usr/lib/x86_64-linux-gnu/libboost_python3.so

RUN git -C src clone \
    -b master \
    https://github.com/ros-drivers/audio_common.git

# ==================================================================
# build ros package source
# ------------------------------------------------------------------
RUN catkin config \
    --extend /opt/ros/$ROS_DISTRO \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.6 \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m \
    -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
    && \
    catkin build

RUN mkdir -p /root/local_mount/
RUN ln -s /root/harmoni_catkin_ws/src/HARMONI /root/local_mount/

# ==================================================================
RUN \
    apt-get update -y && apt-get upgrade -y

# ==================================================================
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
ENTRYPOINT ["/usr/local/bin/dumb-init","--rewrite","15:10","--"]
