# goal definition

uint8 action
uint8 START = 0
uint8 STOP = 1
uint8 REQUEST = 2

string optional_data #usually used for requests
string child_server #specfic action server to use
string condition #TODO-future: convert to enum

---
# result definition
uint8 action
uint8 START = 0
uint8 STOP = 1
uint8 REQUEST = 2

bool do_action
string message

---
# feedback
uint8 action
uint8 START = 0
uint8 STOP = 1
uint8 REQUEST = 2

int8 state