FROM harmoniteam/harmoni:kinetic-core

RUN \
    PIP_INSTALL="python3.6 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    dlib \
    imutils \
    facenet-pytorch \
    Pillow

CMD ["/bin/bash"]
