recording:
  audio_data: ["pc_microphone"]
  video_data: ["pc_camera"]
  audio_video_data: ["pc_microphone", "pc_camera"] #It is an array of 2 items: array[0] refers to audio data input, array[1] refers to video data input
  outdir : "/home/micol/resources/" #folder where audio and video data are stored

