# goal definition

uint8 action_type # the type of action. Enums defined in harmoni_common_lib
string optional_data # usually used for requests
string condition #TODO-future: convert to enum

---
# result definition
uint8 action_type # the type of action. Enums defined in harmoni_common_lib
bool do_action # whether the action succeeded
string message

---
# feedback
uint8 action_type # the type of action. Enums defined in harmoni_common_lib
int8 state # state of action server. Enums defined in harmoni_common_lib