name: buildx-manual-base

on:
  workflow_dispatch:
    inputs:
      - ros-version: 'ROS Version to build towards'
      - required: true
      - default: 'noetic'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build the Kinetic images (excluding linux/arm/v7,linux/arm64 for now)
      - name: Run Buildx
        if: github.event.inputs.ros-version == 'kinetic'
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=false" \
            --file ./dockerfiles/harmoni/kinetic/base/dockerfile . \
            --tag harmoniteam/harmoni:kinetic-base

      - name: Login to DockerHub
        # if: success() && github.event_name != 'pull_request'
        if: success() && github.event.inputs.ros-version == 'kinetic'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        # if: success() && github.event_name != 'pull_request'
        if: success() && github.event.inputs.ros-version == 'kinetic'
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --file ./dockerfiles/harmoni/kinetic/base/dockerfile . \
            --tag harmoniteam/harmoni:kinetic-base
      - name: Inspect image
        if: github.event.inputs.ros-version == 'kinetic'
        run: |
          docker buildx imagetools inspect harmoniteam/harmoni:kinetic-base

      # Build the Noetic images
      - name: Run Buildx
        if: github.event.inputs.ros-version == 'noetic'
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=false" \
            --file ./dockerfiles/harmoni/noetic/base/dockerfile . \
            --tag harmoniteam/harmoni:noetic-base

      - name: Login to DockerHub
        # if: success() && github.event_name != 'pull_request'
        if: success() && github.event.inputs.ros-version == 'noetic'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        # if: success() && github.event_name != 'pull_request'
        if: success() && github.event.inputs.ros-version == 'noetic'
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --file ./dockerfiles/harmoni/noetic/base/dockerfile . \
            --tag harmoniteam/harmoni:noetic-base
      - name: Inspect image
        if: github.event.inputs.ros-version == 'noetic'
        run: |
          docker buildx imagetools inspect harmoniteam/harmoni:noetic-base
